### ISSUE TITLE
Create Champions League Tournament

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#556]

**Comment by rjourde** [comment]
As Champions League is a 2 legged tournament. Easiest, fastest and safest way to manage it is to manually add the teams qualified for the next phase.

**Comment by santiaago** [comment]
ok works for me.

**Comment by rjourde** [comment]
F*ck i push directly to master. Sorry :(

**Comment by santiaago** [comment]
hahaha oh well, merge everything

**Comment by santiaago** [comment]
Can we close this?

**Comment by rjourde** [comment]
ja ja
