### ISSUE TITLE
Add logo to team

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#557]

**Comment by santiaago** [comment]
you mean avatar? (tinygraphs?) or icon logo.

**Comment by rjourde** [comment]
like for flag for countries. I mean team badges. I already got them but I don't know if we the right to use them. Non-commercial use so I think it is ok

**Comment by santiaago** [comment]
are there in svg?

**Comment by santiaago** [comment]
I think we should be alright , non commercial use ;)

**Comment by rjourde** [comment]
Done with #556

**Comment by santiaago** [comment]
closing this then
