### ISSUE TITLE
Use tinygraphs as avatar

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#558]
also: add link to tinygraphs.com in footer.

**Comment by santiaago** [comment]
Lets do this now, **tinygraphs** is kind of complete.
Lets try different `themes` and `shapes` and decide what to do.

I would like `space invaders` for **users**, then something different for **teams** (maybe `hexa16`)
and `hexa` for **tournaments**. but feel free to experiment.

**Comment by rjourde** [comment]
yep no problemo. We can do this first!

**Comment by rjourde** [comment]
Can we generate a spaceinvader with random theme ?

**Comment by santiaago** [comment]
We cant do this because we need to return the **same** theme for the same user **each time**.

Try this:
make a **map** **int**: **string**.

    0: "theme0"
    1: "theme1"
    2: "theme2"
    3: "theme3"

Then do: 

~~~go
themeid := (UserId()%3)
return myMap[themeid]
~~~

Then use that **theme** for the **user** or **team**, etc...
