### ISSUE TITLE
Review home page

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#559]
- Add full screen awesome picture
- Move login button to home page

**Comment by santiaago** [comment]
this is almost complete right? what are we missing except for the code review comments?

**Comment by rjourde** [comment]
set the proper image and it's done!

**Comment by santiaago** [comment]
cool, I would like this merge to master when the image and code review are done, to start spoting issues in production :)

**Comment by rjourde** [comment]
I did the changes at work so you will have to wait tomorrow ;)

**Comment by santiaago** [comment]
no problem ;)
