### ISSUE TITLE
Empty home page on navbar brand/home click

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#561]

**Comment by santiaago** [comment]
could you explain more?

**Comment by rjourde** [comment]
Yes I can explain more. if you go to root, you will have an empty page (no
activities) unless you refresh the page.

**Comment by rjourde** [comment]
bad `href` in navbar: should be `/#/` instead of `/#` or `#`.

**Comment by santiaago** [comment]
does that fix it?
