### ISSUE TITLE
activate phase from admin Results tab

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#562]

**Comment by santiaago** [comment]
how do we do this?

**Comment by rjourde** [comment]
add new admin endpoints (/admin/activatePhase?phase="SemiFinals") and we set IsReady = true on each match of the given phase.

**Comment by santiaago** [comment]
ok.

**Comment by santiaago** [comment]
is this done?

**Comment by rjourde** [comment]
not yet
