### ISSUE TITLE
Team leaves tournament activity message is wrong

### ISSUE THREAD

**Issue by santiaago** [santiaago/gonawin#626]
When a team leaves a tournament, the activity should be for the team and not for the user:

Currenly:

    UserA left tournament TournamentA
    TeamA joined tournament TournamentA

It should be:

    TeamA left tournament TournamentA
    TeamA joined tournament TournamentA

![screen shot 2015-05-31 at 15 53 59](https://cloud.githubusercontent.com/assets/825563/7902298/7b285e4e-07ad-11e5-91a1-8f49fbebe596.png)

**Comment by rjourde** [comment]
PR reviewed. tested. deployed.
