### ISSUE TITLE
do not show "New tournament" button

### ISSUE THREAD

**Issue by santiaago** [santiaago/gonawin#628]
`New Tournament` button should not appear as this functionality is not used right now.

**Comment by rjourde** [comment]
Only displayed for gonawin admin

**Comment by santiaago** [comment]
When I login with a fake email and no admin flag I still see the button.

**Comment by rjourde** [comment]
Ah yes it's a problem

**Comment by rjourde** [comment]
PR accepted, tested and deployed.
