### ISSUE TITLE
deny invitation button does not work

### ISSUE THREAD

**Issue by santiaago** [santiaago/gonawin#635]
workflow
- userA invites userB to team
- userB receives invitation and "denies it" in his profile

problems:
* notification does not go away
* invitation line does not go away

**Comment by santiaago** [comment]
@rjourde when you re wrote the front end all logic of inviting a user went away (and I am unable to find it..). So we cannot fix this until we fix the `User invitation` regression....

**Comment by santiaago** [comment]
blocked by #619

**Comment by rjourde** [comment]
In UserShowCtrl, `denyInvitation`:
~~~ javascript
if(!$scope.userData.Invitations[index].show) {
  return;
}
~~~
should be
~~~ javascript
if(!$scope.userData.Invitations[index].handled) {
  return;
}
~~~

**Comment by santiaago** [comment]
do it

**Comment by rjourde** [comment]
still blocked by #619...

**Comment by rjourde** [comment]
depllyed.
