### ISSUE TITLE
tournament should also have ranking by user's teams

### ISSUE THREAD

**Issue by santiaago** [santiaago/gonawin#659]

**Comment by santiaago** [comment]
I think we should remove the Teams tab from the ranking at the same time.

Do you agree @rjourde 
![screen shot 2015-06-19 at 23 10 40](https://cloud.githubusercontent.com/assets/825563/8263971/7f06b288-16d8-11e5-801b-d202c9478be2.png)

**Comment by rjourde** [comment]
Yes

**Comment by rjourde** [comment]
merged but not deployed due to 2 issues:
* tab bar User/Teams is broken (no active state)
* global is ranking is ok but not for teams (points are global and not per tournament)

**Comment by santiaago** [comment]
don't merge if there are issues..

**Comment by rjourde** [comment]
I saw them after 😅

**Comment by santiaago** [comment]
I fixed one of the issues, 
could you explain this? _tab bar User/Teams is broken (no active state)_

**Comment by rjourde** [comment]
deployed.
