### ISSUE TITLE
Leave tournament is useless

### ISSUE THREAD

**Issue by rjourde** [santiaago/gonawin#674]
* remove 'leave tournament' button + related javascript [frontend]
* delete leave tournament handler [backend]

**Comment by santiaago** [comment]
Hide button for now, we will delete handler later on,
right now the joinButton is used in such a way that you need a `join` and `leave` function.

**Comment by santiaago** [comment]
changed my mind, I removed the backend code as well.

**Comment by rjourde** [comment]
PR #686 tested, merged. Deployed.

**Comment by santiaago** [comment]
:+1:
